server:
  port: 8091

location: D:/upLoad/picture/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maths?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      min-idle: 5
      max-active: 10
      max-wait: 5000
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局策略配置，全部都是用auto策略(数据库ID自增长)
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.yzc.entities

# 配置日志级别
logging:
  com.shouyi: info